### ISSUE TITLE
Overwriting dataTransfer data on 'clipboardInput' event seems to have no effect on pasting

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor5-clipboard#52]
According to the [clipboard docs](https://ckeditor.com/docs/ckeditor5/latest/api/module_clipboard_clipboard-Clipboard.html)  which shows the way to preprocess the clipboard data:

```js
this.listenTo( editor.editing.view, 'clipboardInput', ( evt, data ) => {
    const content = customTransform( data.dataTransfer.get( 'text/html' ) );
    const transformedContent = transform( content );
    data.dataTransfer.set( 'text/html', transformedContent );
} );
```

and also looking at the clipboard code: https://github.com/ckeditor/ckeditor5-clipboard/blob/c077719bd6cb4acda6301a4966d6c090940d53c2/src/clipboard.js#L145-L178

it seems the intention here is that **one can overwrite what's inside data transfer object so it will be pasted inside the editor**. However, I am unable to make this work, it seems that native data transfer does not allow changing its data in those scenarios. Check this codepen - https://codepen.io/f1ames/pen/MBNKEo?editors=1010

On Chrome data is not simply changed and on FF it throws `NoModificationAllowedError: Modifications are not allowed for this document`.

**Comment by Reinmar** [comment]
I wonder whether it'd be better to rewrite that code snippet mentioned in the docs or add support for always available `DataTransfer#setData()` (that's our facade, so we can mock this). Since we should KISS, if we can change that code snippet, that'd be the way to go.

**Comment by f1ames** [comment]
We can change the snippet (we should because the code does not work). The question is if there is any other reliable way to pre-process data in the `clipboardInput` event and then pass it further? How do you inject it into the clipboard pipeline so the further events will use it? I don't see any simple way after quick look 🤔

**Comment by f1ames** [comment]
And on `inputTransformation` event there is data which was already processed by `Clipboard` plugin (and no `dataTransfer` object) so you cannot access raw data from clipboard there. So docs should be changed, but we also need a reasonable way to pre-process raw clipboard data and pass it along to clipboard pipeline which means:

> add support for always available DataTransfer#setData()

will be needed probably.

**Comment by f1ames** [comment]
☝️ Yes, I think we could do this, haven't thought about that TBH. It makes sense in this case 👍 

So we are just left with incorrect docs. Should it be adjusted to suggest the above method also?

**Comment by Reinmar** [comment]
Yup. Once we'll create it we can change the docs.

**Comment by f1ames** [comment]
@Reinmar just one more thing, I refactored the sample you posted and it looks like this:

```js
this.listenTo( editor.editing.view.document, 'clipboardInput', ( evt, data ) => {
    evt.stop();

    const htmlData = customTransform( data.dataTransfer.get( 'text/html' ) );
    const transformedContent = transform( htmlData );
    const content = htmlDataProcessorInstance.toView( content );

    editor.plugins.get( 'Clipboard' ).fire( 'inputTransformation', { content } );
} );
```

I have some doubts, because of the fact that `inputTransformation` needs a `View` instance. So each time you would like to plug in to `clipboardInput` you need `HtmlDataProcessor` instance and you need to manual parse `content` to view and pass it (now it happens automatically inside default listener). And also you need to remember to stop the event propagation. It is rather simple but still adds some additional procedures making it more complex to integrate with.

---

No if we will add `dataTransfer` as second parameter as we talked F2F this will be yet another thing, again making it more complex.

And then you will have `dataTransfer` object in both `clipboardInput` and `inputTransformation` events. How do you decide (as a developer) which event you should listen to, to fiddle with clipboard data as both have `dataTransfer` object so basically in both you can do anything you want with the data.

Now, [the `clipboardInput` is responsible for extracting data from `dataTransfer`](https://github.com/ckeditor/ckeditor5-clipboard/blob/922d8e8066f3d64d8f9396698f0c5497eeb698e1/src/clipboard.js#L145), but if `dataTransfer` will be available in `inputTransforamtion` the same can be done there, which makes me unsure about this change. WDYT?

I know I have covered two topics here, but they are both connected to this issue and the way how clipboard works (and how we would like to use it).

**Comment by Reinmar** [comment]
I worked on the docs a bit in 75f4eb7. I got rid of that incorrect example. However, we still need to think whether what to do with that event.

**Comment by Reinmar** [comment]
OTOH, if the only reason to listen to `clipboardInput` is to upload pasted/dropped files... then perhaps we don't need to expose this `getClipboardContent()` and `insertContent()` methods? Maybe no one will ever use them?

**Comment by f1ames** [comment]
After F2F talk with @Reinmar we concluded that for now we will work to improve the docs so it is more clear which event (`clipboardInput` and `inputTransformation`) should be used in what cases. The only change  will be providing `dataTransfer` object for `inputTransformation` event listeners.

**Comment by Reinmar** [comment]
I've rewritten those docs completely and we should be fine now.
