### ISSUE TITLE
Paste feature  is not work

### ISSUE THREAD

**Issue by maytinhdibo** [ckeditor/ckeditor5-clipboard#65]
It's my config.
`plugins: [Essentials, Clipboard ,Heading, Bold, Table, TableToolbar, Italic, Paragraph, FontFamily, BlockQuote, FontSize, FontColor, Image, ImageCaption, ImageStyle, Link, List, ImageToolbar, ImageUpload, Alignment, Base64UploadAdapter]
`
And when i use paste or Ctrl+P

![image](https://user-images.githubusercontent.com/6669725/60965653-879da200-a340-11e9-844a-2f9ccd7b46ed.png)

**Comment by Mgsy** [comment]
Hi, I can't reproduce your issue. Can you give us more information about your integration, `package.json`, what kind of content you try to paste? Code samples will be also much appreciated.

**Comment by maytinhdibo** [comment]
It's is my `package.json`. But when I don't use any plugin it will be working well. My content can be text or just content is ckeditor. 
`"dependencies": {
    "@babel/core": "7.4.3",
    "@babel/plugin-transform-react-jsx": "^7.3.0",
    "@babel/plugin-transform-react-jsx-self": "^7.2.0",
    "@ckeditor/ckeditor5-alignment": "^11.1.2",
    "@ckeditor/ckeditor5-basic-styles": "^11.1.2",
    "@ckeditor/ckeditor5-block-quote": "^11.1.1",
    "@ckeditor/ckeditor5-build-classic": "^12.3.0",
    "@ckeditor/ckeditor5-clipboard": "^12.0.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.1",
    "@ckeditor/ckeditor5-editor-classic": "^12.1.2",
    "@ckeditor/ckeditor5-essentials": "^11.0.3",
    "@ckeditor/ckeditor5-font": "^11.2.0",
    "@ckeditor/ckeditor5-heading": "^11.0.3",
    "@ckeditor/ckeditor5-highlight": "^11.0.3",
    "@ckeditor/ckeditor5-image": "^13.1.1",
    "@ckeditor/ckeditor5-link": "^11.1.0",
    "@ckeditor/ckeditor5-list": "^12.0.3",
    "@ckeditor/ckeditor5-paragraph": "^11.0.3",
    "@ckeditor/ckeditor5-react": "^1.1.3",
    "@ckeditor/ckeditor5-table": "^13.0.1",
    "@ckeditor/ckeditor5-ui": "^13.0.1",
    "@ckeditor/ckeditor5-upload": "^11.1.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.19",
    "@fortawesome/free-solid-svg-icons": "^5.9.0",
    "@fortawesome/react-fontawesome": "^0.1.4",
    "@svgr/webpack": "4.1.0",
    "@typescript-eslint/eslint-plugin": "1.6.0",
    "@typescript-eslint/parser": "1.6.0",
    "babel-eslint": "10.0.1",
    "babel-jest": "^24.8.0",
    "babel-loader": "8.0.5",
    "babel-plugin-named-asset-import": "^0.3.2",
    "babel-preset-react-app": "^9.0.0",
    "bootstrap": "^4.3.1",
    "camelcase": "^5.2.0",
    "case-sensitive-paths-webpack-plugin": "2.2.0",
    "chart.js": "^2.8.0",
    "css-loader": "2.1.1",
    "dotenv": "6.2.0",
    "dotenv-expand": "4.2.0",
    "eslint": "^5.16.0",
    "eslint-config-react-app": "^4.0.1",
    "eslint-loader": "2.1.2",
    "eslint-plugin-flowtype": "2.50.1",
    "eslint-plugin-import": "2.16.0",
    "eslint-plugin-jsx-a11y": "6.2.1",
    "eslint-plugin-react": "7.12.4",
    "eslint-plugin-react-hooks": "^1.5.0",
    "file-loader": "3.0.1",
    "fs-extra": "7.0.1",
    "html-webpack-plugin": "4.0.0-beta.5",
    "identity-obj-proxy": "3.0.0",
    "is-wsl": "^1.1.0",
    "jest": "24.7.1",
    "jest-environment-jsdom-fourteen": "0.1.0",
    "jest-resolve": "24.7.1",
    "jest-watch-typeahead": "0.3.0",
    "mini-css-extract-plugin": "0.5.0",
    "node-sass": "^4.12.0",
    "optimize-css-assets-webpack-plugin": "5.0.1",
    "pnp-webpack-plugin": "1.2.1",
    "postcss-flexbugs-fixes": "4.1.0",
    "postcss-loader": "3.0.0",
    "postcss-normalize": "7.0.1",
    "postcss-preset-env": "6.6.0",
    "postcss-safe-parser": "4.0.1",
    "react": "^16.8.6",
    "react-app-polyfill": "^1.0.1",
    "react-chartjs-2": "^2.7.6",
    "react-dev-utils": "^9.0.1",
    "react-dom": "^16.8.6",
    "react-quill": "^1.3.3",
    "react-router": "^5.0.1",
    "react-router-dom": "^5.0.1",
    "react-select": "^3.0.4",
    "react-table": "^6.10.0",
    "reactstrap": "^8.0.0",
    "resolve": "1.10.0",
    "sass-loader": "7.1.0",
    "semver": "6.0.0",
    "style-loader": "0.23.1",
    "terser-webpack-plugin": "1.2.3",
    "ts-pnp": "1.1.2",
    "url-loader": "1.1.2",
    "webpack": "4.29.6",
    "webpack-dev-server": "3.2.1",
    "webpack-manifest-plugin": "2.0.4",
    "workbox-webpack-plugin": "4.2.0"
  }`

**Comment by maytinhdibo** [comment]
> Hi, I can't reproduce your issue. Can you give us more information about your integration, `package.json`, what kind of content you try to paste? Code samples will be also much appreciated.

Here is full config.
```
const editorConfiguration = {
    plugins: [Essentials, Clipboard ,Heading, Bold, Table, TableToolbar, Italic, Paragraph, FontFamily, BlockQuote, FontSize, FontColor, Image, ImageCaption, ImageStyle, Link, List, ImageToolbar, ImageUpload, Alignment, Base64UploadAdapter],
    toolbar: ['Heading', '|', 'Bold', 'Italic', 'link', '|', 'Clipboard', 'FontFamily', 'FontSize', 'FontColor', '|', 'Alignment', 'insertTable', 'imageUpload', 'list', 'ListUI', 'BlockQuote', 'Undo', 'Redo', 'Paragraph', 'Agliment'],
    heading: {
        options: [
            { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
            { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
            { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' }
        ]
    }, image: {
        toolbar: [
            'imageStyle:full',
            'imageStyle:side',
            '|',
            'imageTextAlternative'
        ]
    }, fontSize: {
        options: [10, 11, 12, 13, 14, 16, 18, 24, 28, 32]
    },
    table: {
        contentToolbar: [ 'tableColumn', 'tableRow', 'mergeTableCells' ]
    },
    language: 'vi'
};
```

**Comment by Mgsy** [comment]
As I can see, you use React in your application. Just to be sure - did you follow our [React integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html)? Does this issue exist after performing steps from this guide? If so, did you make some extra steps in your project?

**Comment by ma2ciek** [comment]
@maytinhdibo,

Please try to attach as much useful information as you can while opening the issue. It's the same situation as in https://github.com/ckeditor/ckeditor5/issues/1872. We don't have any crystal ball and we can only guess based on the provided information.

**Comment by maytinhdibo** [comment]
> @maytinhdibo,
> 
> Please try to attach as much useful information as you can while opening the issue. It's the same situation as in [ckeditor/ckeditor5#1872](https://github.com/ckeditor/ckeditor5/issues/1872). We don't have any crystal ball and we can only guess based on the provided information.

I understand this problem, I follow your guide (although it's confusing), but when I remove this package in my package.json, paste feature is working.
`"@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.1"`

**Comment by maytinhdibo** [comment]
This is my new package.json, it's working and I copy from https://github.com/ckeditor/ckeditor5-react-example 
`"@ckeditor/ckeditor5-alignment": "^11.1.2",
    "@ckeditor/ckeditor5-basic-styles": "^11.1.3",
    "@ckeditor/ckeditor5-block-quote": "^11.1.1",
    "@ckeditor/ckeditor5-build-classic": "^12.3.0",
    "@ckeditor/ckeditor5-clipboard": "^12.0.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.1",
    "@ckeditor/ckeditor5-editor-classic": "^12.1.3",
    "@ckeditor/ckeditor5-essentials": "^11.0.4",
    "@ckeditor/ckeditor5-font": "^11.2.0",
    "@ckeditor/ckeditor5-heading": "^11.0.3",
    "@ckeditor/ckeditor5-highlight": "^11.0.3",
    "@ckeditor/ckeditor5-image": "^13.1.1",
    "@ckeditor/ckeditor5-link": "^11.1.0",
    "@ckeditor/ckeditor5-list": "^12.0.3",
    "@ckeditor/ckeditor5-paragraph": "^11.0.4",
    "@ckeditor/ckeditor5-react": "^1.1.3",
    "@ckeditor/ckeditor5-table": "^13.0.1",
    "@ckeditor/ckeditor5-ui": "^13.0.1",
    "@ckeditor/ckeditor5-upload": "^11.1.0",`

**Comment by Mgsy** [comment]
We're glad you managed to solve your issue.
